// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5pbMlMHHdCL1y-efArLoILClW56ZI0Zw',
    appId: '1:895454038383:web:558d9cf51c3ac7045e809a',
    messagingSenderId: '895454038383',
    projectId: 'ecommerceapp-2fb89',
    authDomain: 'ecommerceapp-2fb89.firebaseapp.com',
    storageBucket: 'ecommerceapp-2fb89.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoYWMqHv_-bkmImgs64jHHk7xHHs1E74M',
    appId: '1:895454038383:android:c415561136be7a5c5e809a',
    messagingSenderId: '895454038383',
    projectId: 'ecommerceapp-2fb89',
    storageBucket: 'ecommerceapp-2fb89.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkf7bK-AEN-9BFEUvP2sQGV_0U-0vvG8U',
    appId: '1:895454038383:ios:ea8a26d21b6981925e809a',
    messagingSenderId: '895454038383',
    projectId: 'ecommerceapp-2fb89',
    storageBucket: 'ecommerceapp-2fb89.appspot.com',
    androidClientId: '895454038383-qc49v4ao6kirak5isc430tu09ju509sn.apps.googleusercontent.com',
    iosClientId: '895454038383-l831bg091j48a2pj7ksh724m12m3kh2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkf7bK-AEN-9BFEUvP2sQGV_0U-0vvG8U',
    appId: '1:895454038383:ios:5993a17097c820ed5e809a',
    messagingSenderId: '895454038383',
    projectId: 'ecommerceapp-2fb89',
    storageBucket: 'ecommerceapp-2fb89.appspot.com',
    androidClientId: '895454038383-qc49v4ao6kirak5isc430tu09ju509sn.apps.googleusercontent.com',
    iosClientId: '895454038383-nk7slg43gldc0a559o7gs3n6dp47kvgh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecomerceApp.RunnerTests',
  );
}
